export const environment = {
  production: true,
  Domain: 'http://localhost/UPAAPI/',
  Login: "http://localhost/UPAAPI/api/Account/login",
  SortAssetDetail: "http://localhost/UPAAPI/api/AssetDetails/SortAssetDetail",
  ListGovernorates: "http://localhost/UPAAPI/api/Governorate/ListGovernorates",
  FilterDataByDepartmentBrandSupplierIdAndPaging: "http://localhost/UPAAPI/api/AssetDetails/FilterDataByDepartmentBrandSupplierIdAndPaging",
  GroupAssetDetailsByBrand: "http://localhost/UPAAPI/api/AssetDetails/GroupAssetDetailsByBrand",
  GroupAssetDetailsByGovernorate: "http://localhost/UPAAPI/api/AssetDetails/GroupAssetDetailsByGovernorate",
  GroupAssetDetailsByOrganization: "http://localhost/UPAAPI/api/AssetDetails/GroupAssetDetailsByOrganization",
  GroupAssetDetailsByHospital: "http://localhost/UPAAPI/api/AssetDetails/GroupAssetDetailsByHospital",
  GroupAssetDetailsBySubOrganization: "http://localhost/UPAAPI/api/AssetDetails/GroupAssetDetailsBySubOrganization",
  ListGovernoratesModel: "http://localhost/UPAAPI/api/Governorate/ListGovernoratesModel",
  ListOrganizations: "http://localhost/UPAAPI/api/Organization/ListOrganizations",
  GenerateOrgcode: "http://localhost/UPAAPI/api/Organization/GenerateOrgcode",
  ListCategories: "http://localhost/UPAAPI/api/Category/ListCategories",
  ListBrands: "http://localhost/UPAAPI/api/Brand/ListBrands",
  ListMasterAssetsWithNofilter: "http://localhost/UPAAPI/api/MasterAsset/ListMasterAssetsWithNofilter",
  GetAssetsByBrandId: "http://localhost/UPAAPI/api/AssetDetails/GetAssetsByBrandId",
  GetAssetsByGovId: "http://localhost/UPAAPI/api/AssetDetails/GetAssetsByGovId",
  GetAssetsByHosId: "http://localhost/UPAAPI/api/AssetDetails/GetAssetsByHosId",
  GetAssetsBySubOrgId: "http://localhost/UPAAPI/api/AssetDetails/GetAssetsBySubOrgId",
  GetAssetsByOrgId: "http://localhost/UPAAPI/api/AssetDetails/GetAssetsByOrgId",
  GetAssetsByUserIdAndPaging: 'http://localhost/UPAAPI/api/AssetDetails/GetAssetsByUserIdAndPaging/',
  SortAssetDetailAfterSearch: "http://localhost/UPAAPI/api/AssetDetails/SortAssetDetailAfterSearch",
  SortMasterAssetafterSearch: "http://localhost/UPAAPI/api/MasterAsset/SortMasterAssetafterSearch",

  GetCountOfAssetByOrganizationGovernorate: "http://localhost/UPAAPI/api/CountOfAsset/GetCountOfAssetByOrganizationGovernorate",
  GetCountOfAssetByCategoryGovernorate: "http://localhost/UPAAPI/api/CountOfAsset/GetCountOfAssetByCategoryGovernorate",
  CategoryPivotTable: "http://localhost/UPAAPI/api/CountOfAsset/CategoryPivotTable",
  CreateCountOfAssets: "http://localhost/UPAAPI/api/CountOfAsset/CreateCountOfAssets",
  SaveRecordCountOfAssets: "http://localhost/UPAAPI/api/CountOfAsset/SaveRecordCountOfAssets",
  UpdateCountOfAsset: "http://localhost/UPAAPI/api/CountOfAsset/UpdateCountOfAsset",
  GetCountOfAssetById: "http://localhost/UPAAPI/api/CountOfAsset/GetCountOfAssetById/",
  DeleteCountOfAsset: "http://localhost/UPAAPI/api/CountOfAsset/DeleteCountOfAsset/",
  GetCountOfAssets: "http://localhost/UPAAPI/api/CountOfAsset?",

  SortAssetsWithoutSearch: "http://localhost/UPAAPI/api/AssetDetails/SortAssetsWithoutSearch/",
  GetHospitalByGovId: "http://localhost/UPAAPI/api/Hospital/GetHospitalByGovId/",
setting:"http://localhost/UPAAPI/api/Settings/Login",
  AddOrganization: "http://localhost/UPAAPI/api/Organization/AddOrganization",
  GetOrganizationById: "http://localhost/UPAAPI/api/Organization/GetById/",
  UpdateOrganization: "http://localhost/UPAAPI/api/Organization/UpdateOrganization",
  DeleteOrganization: "http://localhost/UPAAPI/api/Organization/DeleteOrganization/",

  ListSubOrganizations: "http://localhost/UPAAPI/api/SubOrganization/ListSubOrganizations",
  GenerateSubcode: "http://localhost/UPAAPI/api/SubOrganization/GenerateSubcode",
  AddSubOrganization: "http://localhost/UPAAPI/api/SubOrganization/AddSubOrganization",
  GetSubOrganizationById: "http://localhost/UPAAPI/api/SubOrganization/GetById/",
  GetSubOrganizationByOrgId: "http://localhost/UPAAPI/api/SubOrganization/GetSubOrganizationByOrgId/",
  UpdateSubOrganization: "http://localhost/UPAAPI/api/SubOrganization/UpdateSubOrganization",
  DeleteSubOrganization: "http://localhost/UPAAPI/api/SubOrganization/DeleteSubOrganization/",
  GetOrganizationBySubId: "http://localhost/UPAAPI/api/SubOrganization/GetOrganizationBySubId/",
  DrawChart:"http://localhost/UPAAPI/api/AssetDetails/DrawingChart",
  DrawChartByGov:"http://localhost/UPAAPI/api/AssetDetails/DrawingChartByGov",
  DrawChartForGovAndPopulation:"http://localhost/UPAAPI/api/AssetDetails/DrawChartForGovAndPopulation",
  AddGovernorate: "http://localhost/UPAAPI/api/Governorate/AddGovernorate",
  GetGovernorateById: "http://localhost/UPAAPI/api/Governorate/GetById/",
  GetGovernorateByName: "http://localhost/UPAAPI/api/Governorate/GetGovernorateByName/",
  UpdateGovernorate: "http://localhost/UPAAPI/api/Governorate/UpdateGovernorate",
  DeleteGovernorate: "http://localhost/UPAAPI/api/Governorate/DeleteGovernorate/",

  ListCities: "http://localhost/UPAAPI/api/City/ListCities",
  AddCity: "http://localhost/UPAAPI/api/City/AddCity",
  GetCityById: "http://localhost/UPAAPI/api/City/GetById/",
  UpdateCity: "http://localhost/UPAAPI/api/City/UpdateCity",
  DeleteCity: "http://localhost/UPAAPI/api/City/DeleteCity/",
  getCityIdByName: 'http://localhost/UPAAPI/api/City/GetCityIdByName/',
  GetCitiesByGovernorateId: "http://localhost/UPAAPI/api/City/GetCitiesByGovernorateId/",
  GetAllLstHospitals: "http://localhost/UPAAPI/api/Hospital/GetAllLstHospitals",
  ListHospitals: "http://localhost/UPAAPI/api/Hospital/ListHospitals",
  GetHospitalById: "http://localhost/UPAAPI/api/Hospital/GetById/",
  UpdateHospital: "http://localhost/UPAAPI/api/Hospital/UpdateHospital/",
  DeleteHospital: "http://localhost/UPAAPI/api/Hospital/DeleteHospital/",
  AddHospital: "http://localhost/UPAAPI/api/Hospital/AddHospital",
  GenerateHospitalCode: "http://localhost/UPAAPI/api/Hospital/GenerateHospitalCode",
  AutoCompleteHospitalName:"http://localhost/UPAAPI/api/Hospital/AutoCompleteHospitalName/",
  GetHospitalDetailById: "http://localhost/UPAAPI/api/Hospital/GetHospitalDetailById/",
  GetHospitalsByUserId: "http://localhost/UPAAPI/api/Hospital/GetHospitalsByUserId/",
  GetHospitalsByCityId: "http://localhost/UPAAPI/api/Hospital/GetHospitalsByCityId/",
  GetHospitalsBySubOrganizationId: "http://localhost/UPAAPI/api/Hospital/GetHospitalsBySubOrganizationId/",
  GetHospitalByAssetId:"http://localhost/UPAAPI/api/Hospital/GetHospitalByAssetId/",

  GetHospitalAssetsByGovIdAndDeptIdAndHospitalId2: "http://localhost/UPAAPI/api/AssetDetails/GetHospitalAssetsByGovIdAndDeptIdAndHospitalId/",




  ListECRIs: "http://localhost/UPAAPI/api/ECRI/ListECRIs",
  AddECRI: "http://localhost/UPAAPI/api/ECRI/AddECRI",
  GetECRIById: "http://localhost/UPAAPI/api/ECRI/GetById/",
  UpdateECRI: "http://localhost/UPAAPI/api/ECRI/UpdateECRI",
  DeleteECRI: "http://localhost/UPAAPI/api/ECRI/DeleteECRI/",


  AddCategory: "http://localhost/UPAAPI/api/Category/AddCategory/",
  GetCategoryById: "http://localhost/UPAAPI/api/Category/GetById/",
  GetCategoryByCategoryTypeId: "http://localhost/UPAAPI/api/Category/GetCategoryByCategoryTypeId/",
  UpdateCategory: "http://localhost/UPAAPI/api/Category/UpdateCategory/",
  DeleteCategory: "http://localhost/UPAAPI/api/Category/DeleteCategory/",
  GenerateCategoryCode: "http://localhost/UPAAPI/api/Category/GenerateCategoryCode",



  ListSubCategories: "http://localhost/UPAAPI/api/SubCategory/ListSubCategories",
  GetSubCategoryByCategoryId: "http://localhost/UPAAPI/api/SubCategory/GetSubCategoryByCategoryId/",
  AddSubCategory: "http://localhost/UPAAPI/api/SubCategory/AddSubCategory/",
  GetSubCategoryById: "http://localhost/UPAAPI/api/SubCategory/GetById/",
  UpdateSubCategory: "http://localhost/UPAAPI/api/SubCategory/UpdateSubCategory/",
  DeleteSubCategory: "http://localhost/UPAAPI/api/SubCategory/DeleteSubCategory/",
  GenerateSubCategoryCode: "http://localhost/UPAAPI/api/SubCategory/GenerateSubCategoryCode",

  
  ListOrigins: "http://localhost/UPAAPI/api/Origin/ListOrigins",
  GetOrigins: "http://localhost/UPAAPI/api/Origin/GetOrigins",
  AddOrigin: "http://localhost/UPAAPI/api/Origin/AddOrigin/",
  GetOriginById: "http://localhost/UPAAPI/api/Origin/GetById/",
  UpdateOrigin: "http://localhost/UPAAPI/api/Origin/UpdateOrigin/",
  DeleteOrigin: "http://localhost/UPAAPI/api/Origin/DeleteOrigin/",
  SortOrigins: 'http://localhost/UPAAPI/api/Origin/SortOrigins/',

  GetBrandById: "http://localhost/UPAAPI/api/Brand/GetById/",
  AddBrand: "http://localhost/UPAAPI/api/Brand/AddBrand",
  UpdateBrand: "http://localhost/UPAAPI/api/Brand/UpdateBrand/",
  DeleteBrand: "http://localhost/UPAAPI/api/Brand/DeleteBrand/",
  GenerateBrandCode: "http://localhost/UPAAPI/api/Brand/GenerateBrandCode",



  ListAssetPeriorities: "http://localhost/UPAAPI/api/AssetPeriority/ListAssetPeriorities",
  FilterCountOfAssets: "http://localhost/UPAAPI/api/CountOfAsset/FilterCountOfAssets",
  FilterCountOfAssetByOrganizationGovernorate: "http://localhost/UPAAPI/api/CountOfAsset/FilterCountOfAssetByOrganizationGovernorate",

  GetAssetsByAgeGroup: "http://localhost/UPAAPI/api/AssetDetails/GetAssetsByAgeGroup",

  ListSuppliers: "http://localhost/UPAAPI/api/Supplier/ListSuppliers",
  AddSupplier: "http://localhost/UPAAPI/api/Supplier/AddSupplier",
  GetSupplierById: "http://localhost/UPAAPI/api/Supplier/GetById/",
  UpdateSupplier: "http://localhost/UPAAPI/api/Supplier/UpdateSupplier",
  DeleteSupplier: "http://localhost/UPAAPI/api/Supplier/DeleteSupplier/",
  CreateSupplierAttachment: "http://localhost/UPAAPI/api/Supplier/CreateSupplierAttachment/",
  GetSupplierAttachmentsBySupplierId: "http://localhost/UPAAPI/api/Supplier/GetSupplierAttachmentsBySupplierId/",
  SortSuppliers: "http://localhost/UPAAPI/api/Supplier/SortSuppliers",
  GenerateSupplierCode: "http://localhost/UPAAPI/api/Supplier/GenerateSupplierCode",




  GetAllAssets: "http://localhost/UPAAPI/api/AssetDetails/GetAllAssets",
  GetLastDocumentForAssetDetailId: 'http://localhost/UPAAPI/api/AssetDetails/GetLastDocumentForAssetDetailId/',
  SortAssets: 'http://localhost/UPAAPI/api/AssetDetails/SortAssets/',
  CreateAssetDetailAttachments: "http://localhost/UPAAPI/api/AssetDetails/CreateAssetDetailAttachments",
  GetAttachmentByAssetDetailId: "http://localhost/UPAAPI/api/AssetDetails/GetAttachmentByAssetDetailId/",
  DeleteAssetDetailAttachment: "http://localhost/UPAAPI/api/AssetDetails/DeleteAssetDetailAttachment/",
  UpdateAsset: "http://localhost/UPAAPI/api/AssetDetails/UpdateAssetDetail",
  AddAsset: "http://localhost/UPAAPI/api/AssetDetails/AddAssetDetail",
  DeleteAsset: "http://localhost/UPAAPI/api/AssetDetails/DeleteAssetDetail/",
  GenerateAssetDetailBarcode: "http://localhost/UPAAPI/api/AssetDetails/GenerateAssetDetailBarcode",
  GetAssetById: "http://localhost/UPAAPI/api/AssetDetails/GetById/",
  GetHospitalAssets: "http://localhost/UPAAPI/api/AssetDetails/GetHospitalAssets/",
  AutoCompleteAssetSerial: "http://localhost/UPAAPI/api/AssetDetails/AutoCompleteAssetSerial/",
  AutoCompleteAssetBarCode: "http://localhost/UPAAPI/api/AssetDetails/AutoCompleteAssetBarCode/",
  ViewAssetById: "http://localhost/UPAAPI/api/AssetDetails/ViewAssetDetailById/",
  PyramidGovernorateChart: "http://localhost/UPAAPI/api/AssetDetails/PyramidGovernorateChart",

  PyramidGovernorateChartByParams: "http://localhost/UPAAPI/api/AssetDetails/PyramidGovernorateChartByParams",
  PyramidGovernoratePopulationChartByParams: "http://localhost/UPAAPI/api/AssetDetails/PyramidGovernoratePopulationChartByParams",
  GetAssetsCountByOrganizationsAndCategories: "http://localhost/UPAAPI/api/AssetDetails/GetAssetsCountByOrganizationsAndCategories",


  getMacAddress: 'http://localhost/UPAAPI/api/Error/GetMacAddress',



  DeleteMasterAssetImage: "http://localhost/UPAAPI/api/MasterAsset/DeleteMasterAssetImage/",
  GetLastDocumentForMsterAssetId: "http://localhost/UPAAPI/api/MasterAsset/GetLastDocumentForMsterAssetId/",
  AddMasterAsset: "http://localhost/UPAAPI/api/MasterAsset/AddMasterAsset",
  DeleteMasterAsset: "http://localhost/UPAAPI/api/MasterAsset/DeleteMasterAsset/",
  CreateMasterAssetAttachments: "http://localhost/UPAAPI/api/MasterAsset/CreateMasterAssetAttachments",
  GetAttachmentByMasterAssetId: "http://localhost/UPAAPI/api/MasterAsset/GetAttachmentByMasterAssetId/",
  DeleteMasterAssetAttachmentById: "http://localhost/UPAAPI/api/MasterAsset/DeleteMasterAssetAttachment/",
  SortMasterAssets: "http://localhost/UPAAPI/api/MasterAsset/SortMasterAssets/",
  UpdateMasterAsset: "http://localhost/UPAAPI/api/MasterAsset/UpdateMasterAsset",
  UpdateMasterAssetImageAfterInsert: "http://localhost/UPAAPI/api/MasterAsset/UpdateMasterAssetImageAfterInsert",
  GenerateMasterAssetcode: "http://localhost/UPAAPI/api/MasterAsset/GenerateMasterAssetcode",
  ListMasterAssets: "http://localhost/UPAAPI/api/MasterAsset/ListMasterAssets",
  GetMasterAssetById: "http://localhost/UPAAPI/api/MasterAsset/GetMasterAssetById/",
  AutoCompleteMasterAssetName: "http://localhost/UPAAPI/api/MasterAsset/AutoCompleteMasterAssetName/",
  DistinctAutoCompleteMasterAssetName: "http://localhost/UPAAPI/api/MasterAsset/DistinctAutoCompleteMasterAssetName/",
  ViewMasterAssetById: "http://localhost/UPAAPI/api/MasterAsset/ViewMasterAsset/",
  ListMasterAssetsByHospitalId: "http://localhost/UPAAPI/api/MasterAsset/ListMasterAssetsByHospitalId/",


  SortAssetsafterSearch: "http://localhost/UPAAPI/api/AssetDetails/SortAssetsafterSearch",
};